Section "ServerFlags"
    Option "AutoAddGPU" "false"
EndSection

Section "Device"
    Identifier "vc4-gpu"
    Driver "modesetting"
    Option "kmsdev" "/dev/dri/card1"
    Option "PrimaryGPU" "true"
    BusID "platform:axi:gpu"
EndSection

Section "Screen"
    Identifier "default-screen"
    Device "vc4-gpu"
EndSection
